### ISSUE TITLE
Relay Compiler inappropriately logs to stdout

### ISSUE THREAD

**Issue by josh** [github/webpack-config-github#10]
The `relay-compiler` includes many hard coded `console.log` statements that look at out place in the webpack logging stream.

https://github.com/facebook/relay/blob/9b7c7d0fecdd831b6d67edd4346ccd028660613d/packages/relay-compiler/graphql-compiler/codegen/CodegenRunner.js#L230
https://github.com/facebook/relay/blob/9b7c7d0fecdd831b6d67edd4346ccd028660613d/packages/relay-compiler/graphql-compiler/codegen/CodegenRunner.js#L237
https://github.com/facebook/relay/blob/9b7c7d0fecdd831b6d67edd4346ccd028660613d/packages/relay-compiler/graphql-compiler/codegen/CodegenRunner.js#L315
https://github.com/facebook/relay/blob/9b7c7d0fecdd831b6d67edd4346ccd028660613d/packages/relay-compiler/codegen/RelayFileWriter.js#L261-L267

##

CC: @koddsson

**Comment by koddsson** [comment]
https://github.com/facebook/relay/pull/2204

**Comment by josh** [comment]
This noise also breaks `webpack --stats > stats.json` as these lines are streamed to `stdout` and correct the JSON output.

**Comment by koddsson** [comment]
https://github.com/danielholmes/relay-compiler-webpack-plugin/pull/25
