### ISSUE TITLE
Fix source-map option in production environment

### ISSUE THREAD

**Issue by josh** [github/webpack-config-github#6]
https://github.com/github/webpack-config-github/blob/1ae512dfc5d833322b08a5b05daf93112d4cd9f5/webpack.config.js#L98-L99

``` js
config.devtool = 'source-map'
```

is crashing for some reason.

##

CC: @koddsson

**Comment by koddsson** [comment]
[Seems to be a issue with the babel minify webpack plugin](https://github.com/webpack-contrib/babel-minify-webpack-plugin/issues/68)
