### ISSUE TITLE
Investigate RelayCompilerWebpackPlugin watchman flag

### ISSUE THREAD

**Issue by josh** [github/webpack-config-github#7]
Settings `watchman` to `true` will crash unless the user has watchman installed. Not a great experience as watchman is an external dependency. Users may not have it installed or environments like production or CI systems won't either. If its truly required, it would be nice if it was an npm dependency. Not sure what the best way to integrate this is.

##

CC: @koddsson

**Comment by koddsson** [comment]
It does seem that the facebook projects tell you to [install `watchman` manually](https://facebook.github.io/relay/docs/relay-compiler.html#setting-up-relay-compiler) as a system dependency which is less then ideal.

Maybe we could write a little prebuild step that will detect your platform and install watchman (if it's missing) from the appropriate place?

**Comment by josh** [comment]
I think this is an area that the webpack plugin can improve this. Webpack already includes a file watching mechanize for triggering rebuilds. It seems unnecessary to use *another* tool.

I'd imagine a way for this to be implemented would be to disable the relay-compiler's watchman, then monitor the `sourceRoot` directory and only retrigger the compiler when it changes.

**Comment by josh** [comment]
https://github.com/danielholmes/relay-compiler-webpack-plugin/pull/9
