### ISSUE TITLE
Relay Compiler is invoked N times

### ISSUE THREAD

**Issue by josh** [github/webpack-config-github#9]
On a [simple example](https://github.com/github/webpack-config-github/tree/master/examples/relay), `Runner.compileAll` is called at least twice.

https://github.com/danielholmes/relay-compiler-webpack-plugin/blob/19959b855b34ec6f0a0d6db27a3ae597b3286a88/src/index.js#L97-L105

Actual logged output.

```
$ cd examples/relay
$ webpack
Parsed default in 0.00s

Writing default
Writer time: 0.03s [0.03s compiling, 0.00s generating, 0.00s extra]
Unchanged: 0 files
Written default in 0.03s
Parsed default in 0.00s

Writing default
Writer time: 0.00s [0.00s compiling, 0.00s generating, 0.00s extra]
Unchanged: 0 files
Written default in 0.00s
```

##

CC: @koddsson

**Comment by koddsson** [comment]
https://github.com/danielholmes/relay-compiler-webpack-plugin/pull/7

**Comment by josh** [comment]
https://github.com/danielholmes/relay-compiler-webpack-plugin/pull/13
